PennantConsulting/IntranetFilter

src/app/app.component.html, src/app/app.component.ts, src/assets/museum-pages-small.json, src/index.html, src/styles.less
3 files changed. Fixes WCMSRD-6948 where the filterHiddenSearch field was required. Now it is not required and has been changed to hiddenSearch.
=> Eric WCMSRD-6974

src/app/app.component.ts
Focus set on the search input in clearFilter().
=> Attempt to prevent screen readout of prior search result count via focus

src/app/app.component.html, src/app/app.component.ts
Captures the "Enter" keypress event to search.
=> 508: Enter keypress to search

src/app/filter.pipe.ts
Should've caught this the first time. I need someone for a code reviewer.
=> Alternate formats may not always exist.

src/app/app.component.html, src/app/app.component.ts, src/app/filter.pipe.ts, src/index.html
Enables labels/filter labels to be hidden. Moved extension function because it didn't belong in the filter.pipe.ts.
=> Created hidden labels function, moved extension function

src/app/app.component.html
Request per Heather. Changed the included SVG and its reference.
=> Changed comments icon from chat_02 to comment3

src/app/app.component.html, src/app/app.component.ts, src/app/mediadata.service.ts
Error handling is mostly caught in the mediadata service, but I thought that should be changed as little as possible and the error handling go to the app component. Markup changes were because of my annoyance with spaces and breaks where I think they shouldn't be. I think there are only two. I can back them out if you wish.
=> Added error handling scenarios, changed a tiny bit of markup

src/app/app.component.html, src/app/app.component.ts, src/app/filter.pipe.ts, src/assets/museum-pages-small.json
Breaking IE changes came when converting selects to dropdowns, the worst of which was in the filter pipe. Fun times.
=> Implemented Hierarchy, replaced all selects with TP4 dropdowns

src/app/app.component.ts, src/app/mediadata.service.ts
As per Heather and Robin's instructions. I also updated the error call to pull all error http error data.
=> Updated error message & http error update

src/app/app.component.html
=> Remove sort field if no options are available

src/app/app.component.html, src/app/app.component.ts
I commented out some earlier code that checked on whether or not a back button or some other key was pressed that prevented a focus on the search results count. That code is now necessary as far as I can tell for now. Having it enabled produced some unintended results. May want to revisit if the issue arises again for some reason.
=> Delay set for finding results with no submit button

src/app/app.component.html
On converting from selects to dropdowns, I forgot to add the href attribute to the anchors. Applying that fixed it.
=> Tabbing through sort & filter options

src/app/app.component.ts
for keystrokes and clicks (was previously just keystrokes)
=> Updated delay when no submit is present

src/app/app.component.html, src/app/app.component.ts, src/index.html
Couldn't hide Alternate Formats, Date field or the date field, and the Alt Language field wasn't matching the key in the JSON, so I updated to just to a case-insenstive field match. Also added Alt Formats and Alt Languages for image in top position cards.
=> [WCMSRD-7089] Update to hidden labels

src/app/app.component.html, src/app/app.component.ts
As per our meeting this morning. Removed padding and margin in key areas as was able to for aesthetics.
=> Updated filter spacing

src/app/app.component.html
=> Readded mb-3 to cards

src/app/app.component.ts
This is an educated guess on a fix. This is a problem that is on dev and test, but isn't a problem on my local environment. The fix appeared to work in console in those environments.
=> Removes scroll to top when a dropdown item is selected

src/app/app.component.ts
=> Scroll to form top now only on pagination

src/app/app.component.html, src/app/app.component.ts
Took longer than I thought. Contains a new needed variable determining root scope for jQuery. Potential scoping issues reduced mitigating future issues.
=> Sort dropdown set to always automatically sort on selection

src/app/app.component.html, src/app/app.component.ts
Result of 508 from Pauline. Focus needed on tabbing for dropdown menus. Submit button was being read twice in the search submit button.
=> Corrected focus and removed extra sr-only tag

src/app/app.component.html, src/app/app.component.ts, src/index.html
This required a great many changes. Please review.
=> Added additional url params

src/app/app.component.html
=> Replaced {{}} syntax with [innerHtml] for html rendering

src/app/app.component.ts
Adds a default label for sort options when values are present.
=> Added default label for missing sort options in JSON

src/app/app.component.html
There isn't a label for the top search and it's inline submit button, so there was a problem for screen readers. Adding an aria-label to those should fix that.
=> Added aria-label for 508

src/app/filter.pipe.ts, src/assets/museum-pages-small.json
Nina noticed the filter was matching on fields where a match couldn't be made. Adding catch for instances where a filtered field has a string value.
=> [WCMSRD-7670] Fixing an overly greedy fitler

src/app/app.component.html
Images to the left or right are asked to be centered on a mobile viewport.
=> Updated spacing on title, title icons & mobile positioning on images

src/app/app.component.html
Don't know if these are the desired icons, but these are the ones I would pick. Will probably need Heather for triage.
=> Replaced search and comment svgs with font icons

src/app/app.component.html
To remove undesired bottom margin
=> Changed comments from p to div

src/app/app.component.html, src/index.html
Reverts PennantConsulting/IntranetFilter#56
=> Revert "Removed hidden labels for example, fixed title alignment"

src/app/app.component.html
This also reworked some of the spacing so that the sort option and the "found x out of y" text is better in line with Heather's original intent.
=> Consolidated image positioning, removed block of code
